import { expect, test } from "vitest";
import GADMclient from "./index";
import GADMgeometry from "./index";


// test("namesExp", () => {
//  expect(GADMclient.getNames("USA", 2, ['USA.34_1']).toBe(new Promise<GADMgeometry>)

//  [
//     { GID: 'USA.34.1_1', NAME: 'Alamance', TYPE: 'County' },
//     { GID: 'USA.34.2_1', NAME: 'Alexander', TYPE: 'County' },
//     { GID: 'USA.34.3_1', NAME: 'Alleghany', TYPE: 'County' },
//     { GID: 'USA.34.4_1', NAME: 'Anson', TYPE: 'County' },
//     { GID: 'USA.34.5_1', NAME: 'Ashe', TYPE: 'County' },
//     { GID: 'USA.34.6_1', NAME: 'Avery', TYPE: 'County' },
//     { GID: 'USA.34.7_1', NAME: 'Beaufort', TYPE: 'County' },
//     { GID: 'USA.34.8_1', NAME: 'Bertie', TYPE: 'County' },
//     { GID: 'USA.34.9_1', NAME: 'Bladen', TYPE: 'County' },
//     { GID: 'USA.34.10_1', NAME: 'Brunswick', TYPE: 'County' },
//     { GID: 'USA.34.11_1', NAME: 'Buncombe', TYPE: 'County' },
//     { GID: 'USA.34.12_1', NAME: 'Burke', TYPE: 'County' },
//     { GID: 'USA.34.13_1', NAME: 'Cabarrus', TYPE: 'County' },
//     { GID: 'USA.34.14_1', NAME: 'Caldwell', TYPE: 'County' },
//     { GID: 'USA.34.15_1', NAME: 'Camden', TYPE: 'County' },
//     { GID: 'USA.34.16_1', NAME: 'Carteret', TYPE: 'County' },
//     { GID: 'USA.34.17_1', NAME: 'Caswell', TYPE: 'County' },
//     { GID: 'USA.34.18_1', NAME: 'Catawba', TYPE: 'County' },
//     { GID: 'USA.34.19_1', NAME: 'Chatham', TYPE: 'County' },
//     { GID: 'USA.34.20_1', NAME: 'Cherokee', TYPE: 'County' },
//     { GID: 'USA.34.21_1', NAME: 'Chowan', TYPE: 'County' },
//     { GID: 'USA.34.22_1', NAME: 'Clay', TYPE: 'County' },
//     { GID: 'USA.34.23_1', NAME: 'Cleveland', TYPE: 'County' },
//     { GID: 'USA.34.24_1', NAME: 'Columbus', TYPE: 'County' },
//     { GID: 'USA.34.25_1', NAME: 'Craven', TYPE: 'County' },
//     { GID: 'USA.34.26_1', NAME: 'Cumberland', TYPE: 'County' },
//     { GID: 'USA.34.27_1', NAME: 'Currituck', TYPE: 'County' },
//     { GID: 'USA.34.28_1', NAME: 'Dare', TYPE: 'County' },
//     { GID: 'USA.34.29_1', NAME: 'Davidson', TYPE: 'County' },
//     { GID: 'USA.34.30_1', NAME: 'Davie', TYPE: 'County' },
//     { GID: 'USA.34.31_1', NAME: 'Duplin', TYPE: 'County' },
//     { GID: 'USA.34.32_1', NAME: 'Durham', TYPE: 'County' },
//     { GID: 'USA.34.33_1', NAME: 'Edgecombe', TYPE: 'County' },
//     { GID: 'USA.34.34_1', NAME: 'Forsyth', TYPE: 'County' },
//     { GID: 'USA.34.35_1', NAME: 'Franklin', TYPE: 'County' },
//     { GID: 'USA.34.36_1', NAME: 'Gaston', TYPE: 'County' },
//     { GID: 'USA.34.37_1', NAME: 'Gates', TYPE: 'County' },
//     { GID: 'USA.34.38_1', NAME: 'Graham', TYPE: 'County' },
//     { GID: 'USA.34.39_1', NAME: 'Granville', TYPE: 'County' },
//     { GID: 'USA.34.40_1', NAME: 'Greene', TYPE: 'County' },
//     { GID: 'USA.34.41_1', NAME: 'Guilford', TYPE: 'County' },
//     { GID: 'USA.34.42_1', NAME: 'Halifax', TYPE: 'County' },
//     { GID: 'USA.34.43_1', NAME: 'Harnett', TYPE: 'County' },
//     { GID: 'USA.34.44_1', NAME: 'Haywood', TYPE: 'County' },
//     { GID: 'USA.34.45_1', NAME: 'Henderson', TYPE: 'County' },
//     { GID: 'USA.34.46_1', NAME: 'Hertford', TYPE: 'County' },
//     { GID: 'USA.34.47_1', NAME: 'Hoke', TYPE: 'County' },
//     { GID: 'USA.34.48_1', NAME: 'Hyde', TYPE: 'County' },
//     { GID: 'USA.34.49_1', NAME: 'Iredell', TYPE: 'County' },
//     { GID: 'USA.34.50_1', NAME: 'Jackson', TYPE: 'County' },
//     { GID: 'USA.34.51_1', NAME: 'Johnston', TYPE: 'County' },
//     { GID: 'USA.34.52_1', NAME: 'Jones', TYPE: 'County' },
//     { GID: 'USA.34.53_1', NAME: 'Lee', TYPE: 'County' },
//     { GID: 'USA.34.54_1', NAME: 'Lenoir', TYPE: 'County' },
//     { GID: 'USA.34.55_1', NAME: 'Lincoln', TYPE: 'County' },
//     { GID: 'USA.34.56_1', NAME: 'Macon', TYPE: 'County' },
//     { GID: 'USA.34.57_1', NAME: 'Madison', TYPE: 'County' },
//     { GID: 'USA.34.58_1', NAME: 'Martin', TYPE: 'County' },
//     { GID: 'USA.34.59_1', NAME: 'McDowell', TYPE: 'County' },
//     { GID: 'USA.34.60_1', NAME: 'Mecklenburg', TYPE: 'County' },
//     { GID: 'USA.34.61_1', NAME: 'Mitchell', TYPE: 'County' },
//     { GID: 'USA.34.62_1', NAME: 'Montgomery', TYPE: 'County' },
//     { GID: 'USA.34.63_1', NAME: 'Moore', TYPE: 'County' },
//     { GID: 'USA.34.64_1', NAME: 'Nash', TYPE: 'County' },
//     { GID: 'USA.34.65_1', NAME: 'NewHanover', TYPE: 'County' },
//     { GID: 'USA.34.66_1', NAME: 'Northampton', TYPE: 'County' },
//     { GID: 'USA.34.67_1', NAME: 'Onslow', TYPE: 'County' },
//     { GID: 'USA.34.68_1', NAME: 'Orange', TYPE: 'County' },
//     { GID: 'USA.34.69_1', NAME: 'Pamlico', TYPE: 'County' },
//     { GID: 'USA.34.70_1', NAME: 'Pasquotank', TYPE: 'County' },
//     { GID: 'USA.34.71_1', NAME: 'Pender', TYPE: 'County' },
//     { GID: 'USA.34.72_1', NAME: 'Perquimans', TYPE: 'County' },
//     { GID: 'USA.34.73_1', NAME: 'Person', TYPE: 'County' },
//     { GID: 'USA.34.74_1', NAME: 'Pitt', TYPE: 'County' },
//     { GID: 'USA.34.75_1', NAME: 'Polk', TYPE: 'County' },
//     { GID: 'USA.34.76_1', NAME: 'Randolph', TYPE: 'County' },
//     { GID: 'USA.34.77_1', NAME: 'Richmond', TYPE: 'County' },
//     { GID: 'USA.34.78_1', NAME: 'Robeson', TYPE: 'County' },
//     { GID: 'USA.34.79_1', NAME: 'Rockingham', TYPE: 'County' },
//     { GID: 'USA.34.80_1', NAME: 'Rowan', TYPE: 'County' },
//     { GID: 'USA.34.81_1', NAME: 'Rutherford', TYPE: 'County' },
//     { GID: 'USA.34.82_1', NAME: 'Sampson', TYPE: 'County' },
//     { GID: 'USA.34.83_1', NAME: 'Scotland', TYPE: 'County' },
//     { GID: 'USA.34.84_1', NAME: 'Stanly', TYPE: 'County' },
//     { GID: 'USA.34.85_1', NAME: 'Stokes', TYPE: 'County' },
//     { GID: 'USA.34.86_1', NAME: 'Surry', TYPE: 'County' },
//     { GID: 'USA.34.87_1', NAME: 'Swain', TYPE: 'County' },
//     { GID: 'USA.34.89_1', NAME: 'Tyrrell', TYPE: 'County' },
//     { GID: 'USA.34.91_1', NAME: 'Vance', TYPE: 'County' },
//     { GID: 'USA.34.92_1', NAME: 'Wake', TYPE: 'County' },
//     { GID: 'USA.34.95_1', NAME: 'Watauga', TYPE: 'County' },
//     { GID: 'USA.34.97_1', NAME: 'Wilkes', TYPE: 'County' },
//     { GID: 'USA.34.98_1', NAME: 'Wilson', TYPE: 'County' },
//     { GID: 'USA.34.99_1', NAME: 'Yadkin', TYPE: 'County' },
//     { GID: 'USA.34.100_1', NAME: 'Yancey', TYPE: 'County' }
//   ]
});